[tool.poetry]
name = "desafio-python-1"
version = "0.1.0"
description = ""
authors = ["Nathan Xavier <nathannery84@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pandas = "^2.3.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
